name: get dependencies
description: Install dependencies for warpfield.

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade build
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      shell: bash
