version: "2"
plugins:
  sonar-python:
    enabled: true
    checks:
      python:S107:
        enabled: false
  pep8:
    enabled: true
    checks:
      E128:     # continuation line under-indented for visual indent
        enabled: false
      E221:     # multiple spaces before operator
        enabled: false
      E701:     # multiple statements with colon
        enabled: false
      E731:     # do not assign a lambda expression
        enabled: false
  radon:
nabled: true
exclude_patterns:
  - "/.*"
  - "/LICENSE"
  - "/README.md"
  - "/setup.py"
  - "/notebook/"
  - "/challenge/"
  - "/tests/**/__init__.py"
  - "*.txt"
  - "*.md"
