[build-system]
requires = ['setuptools>=75.0', 'wheel>=0.44']
build-backend = 'setuptools.build_meta'

[project]
name = 'jasmine_warpfield'
description = 'An experimental code to simulate a warped focal plane'
requires-python = '>=3.10'
license = {file = 'LICENSE'}

authors = [
  { name = 'Ryou Ohsawa', email = 'ryou.ohsawa@nao.ac.jp' }
]

classifiers = [
  'Development Status :: 3 - Alpha',
  'Intended Audience :: Science/Research',
  'License :: OSI Approved :: MIT License',
  'Operating System :: POSIX :: Linux',
  'Programming Language :: Python :: 3',
  'Programming Language :: Python :: 3.10',
  'Programming Language :: Python :: 3.11',
  'Programming Language :: Python :: 3.12',
  'Programming Language :: Python :: 3.13',
  'Topic :: Scientific/Engineering :: Astronomy'
]

dynamic = ['version', 'readme']

dependencies = [
  'numpy>=2.1',
  'h5py>=3.11',
  'scipy>=1.9',
  'pandas>=1.14',
  'astropy>=6.1',
  'astroquery>=0.4',
  'matplotlib>=3.9',
  'shapely>=2.0',
  'jax>=0.4.38',
  'jaxlib>=0.4.38',
  'equinox>=0.13',
  'zodiax>=0.5',
  'numpyro>=0.15',
  'optax>=0.2'
]

[project.optional-dependencies]
test = [
  'pytest>=8.3',
  'hypothesis>=6.54',
  'ruff>=0.12'
]

[project.urls]
homepage = 'https://github.com/JASMINE-Mission/jasmine_warpfield'
repository = 'https://github.com/JASMINE-Mission/jasmine_warpfield'

[tool.setuptools.packages.find]
include = ['warpfield*']

[tool.setuptools.dynamic]
version = { attr = 'warpfield.version.version' }
readme = { file = 'README.md', content-type = 'text/markdown' }


[tool.ruff]
exclude = ['**/test', '**/.skelton.py', 'notebook']
line-length = 79
indent-width = 4

[tool.ruff.lint]
select = [
  'E', 'F', 'W']
ignore = [
  'E221', # multiple spaces before operator
  'E401', # multiple imports on one line
  'E701', # multiple statements on one line
  'E731', # Do not assign a `lambda` expression
  'E741', # Ambiguous variable name
  'F403', # star imports
  'F405', # defined from star imports
]
unfixable = ['ALL']

[tool.ruff.format]
quote-style = 'preserve'
line-ending = 'lf'
preview = true
