name: unittest
description: Check the package integrity via unittest.

runs:
  using: "composite"
  steps:
    - name: Install pytest and dependencies
      env:
        BRANCH: ${{ github.ref_name }}
      run: |
        python -m pip install pytest pytest-html pytest-cov
        if [ -f tests/unittest/requirements.txt ]; then
          pip install -r tests/unittest/requirements.txt;
        fi
      shell: bash

    - name: Test with pytest
      env:
        BRANCH: ${{ github.ref_name }}
      id: pytest
      continue-on-error: true
      run: |
        python -m pytest ./tests/unittest --cov=. --cov-report xml
      shell: bash

    - name: Send Coverage Report to CodeClimate
      if: ${{ steps.pytest.outcome == 'success' && github.event_name == 'push'}}
      uses: paambaati/codeclimate-action@v3.0.0
      env:
        CC_TEST_REPORTER_ID: ${{ env.CC_TEST_REPORTER_ID }}
      with:
        debug: false
        coverageLocations: coverage.xml:coverage.py

    - name: Notice Error
      if: ${{ steps.pytest.outcome == 'failure' }}
      run: exit 1
      shell: bash
