name: unittest
description: Check the package integrity via unittest.

runs:
  using: composite
  steps:
    - name: Install the package
      run: |
        python -m pip install .[test]
      shell: bash

    - name: Check with Ruff
      run: |
        python -m ruff check .
      shell: bash

    - name: Test with pytest
      run: |
        python -m pytest ./tests/unittest
      shell: bash
