name: validation
description: Check the package integrity via validation tests

runs:
  using: composite
  steps:
    - name: Install the package
      run: |
        python -m pip install .[test]
      shell: bash

    - name: Test with pytest
      run: |
        python -m pytest ./tests/validation/ --hypothesis-explain --hypothesis-show-statistics
      shell: bash
