name: notebook
description: Check if the notebooks are successfully executed.

runs:
  using: "composite"
  steps:
    - name: Install Jupyter Lab
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install jupyter jupyterlab nbconvert
      shell: bash

    - name: Execute Jupyter notebook
      run: |
        cd notebook;
        bash ./update.sh
      shell: bash
