name: notebook
description: Check if the notebooks are successfully executed.

runs:
  using: composite
  steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .
        python -m pip install jupyter nbconvert
      shell: bash

    - name: Execute Jupyter notebook
      run: |
        set -e
        cd notebook
        for notebook in *.ipynb
        do
          echo updating "$notebook"
          jupyter nbconvert \
            --to notebook \
            --inplace \
            --execute \
            "$notebook"
        done
      shell: bash
