name: notebook

on:
  workflow_dispatch:
  schedule:
    - cron: '0 13 * * *'

jobs:
  notebook:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: notebook
      uses: ./.github/actions/notebook
